services:
  - type: web
    name: videosplice-backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: HF_API_TOKEN
        sync: false
      - key: HF_API_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
